name: 'Slack Post Action'
description: 'This is a GitHub Action to post to Slack.'
author: 'Hiroyuki Kusu'
branding:
  icon: 'bell'
  color: 'white'
inputs:
  channel:
    description: ''
    required: true
  message:
    description: ''
    required: false
  user_name:
    description: ''
    required: false
  user-name:
    description: ''
    required: false
  user_icon:
    description: ''
    required: false
  user-icon:
    description: ''
    required: false
  color:
    description: ''
    required: false
  author_name:
    description: ''
    required: false
  author-name:
    description: ''
    required: false
  author_link:
    description: ''
    required: false
  author-link:
    description: ''
    required: false
  author_icon:
    description: ''
    required: false
  author-icon:
    description: ''
    required: false
  title:
    description: ''
    required: false
  title_link:
    description: ''
    required: false
  title-link:
    description: ''
    required: false
  body:
    description: ''
    required: false
  fields:
    description: ''
    default: '[]'
    required: false
  image:
    description: ''
    required: false
  thumbnail:
    description: ''
    required: false
  footer:
    description: ''
    default: <${{ github.event.repository.html_url }}|${{ github.event.repository.full_name }}>
    required: false
  footer_icon:
    description: ''
    default: https://github.com/${{ github.event.repository.owner.login }}.png
    required: false
  footer-icon:
    description: ''
    default: https://github.com/${{ github.event.repository.owner.login }}.png
    required: false
  actions:
    description: ''
    default: '[]'
    required: false
  log_button:
    description: ''
    required: false
  log-button:
    description: ''
    required: false
  sha:
    description: ''
    required: false
  report-sha:
    description: ''
    required: false
  event:
    description: ''
    default: ${{ toJson(github.event) }}
    required: false
  run-id:
    description: ''
    default: ${{ github.run_id }}
    required: false
  github-token:
    description: ''
    default: ${{ github.token }}
    required: false
outputs:
  result:
    description: '`success` or `failure` is set.'
runs:
  using: 'node12'
  main: 'dist/index.js'
