name: 'post slack action'
description: 'Post to Slack'
inputs:
  channel:
    description: 'channel'
    required: true
  text:
    description: 'text'
    required: true
  username:
    description: 'username'
    required: false
    default: 'GitHub Actions'
  icon_url:
    description: 'icon url'
    required: false
    default: 'https://github.com/actions.png?size=48'
  color:
    description: 'color'
    required: false
  author_name:
    description: 'author name'
    required: false
  author_link:
    description: 'author link'
    required: false
  author_icon:
    description: 'author icon'
    required: false
  title:
    description: 'title'
    required: false
  title_link:
    description: 'title link'
    required: false
  footer:
    description: 'footer'
    required: false
  footer_icon:
    description: 'footer icon'
    required: false
  fields:
    description: 'fields'
    required: false
  actions:
    description: 'actions'
    required: false
outputs:
  result:
    description: 'result'
  debug:
    description: 'debug'
runs:
  using: 'node12'
  main: 'dist/index.js'
