name: 'Slack Post Action'
description: 'This is a GitHub Action to post to Slack.'
author: 'Hiroyuki Kusu'
branding:
  icon: 'bell'
  color: 'white'
inputs:
  channel:
    description: ''
    required: true
  message:
    description: ''
    required: false
  user_name:
    description: ''
    required: false
  user_icon:
    description: ''
    required: false
  color:
    description: ''
    required: false
  author_name:
    description: ''
    required: false
  author_link:
    description: ''
    required: false
  author_icon:
    description: ''
    required: false
  title:
    description: ''
    required: false
  title_link:
    description: ''
    required: false
  body:
    description: ''
    required: false
  fields:
    description: ''
    required: false
  image:
    description: ''
    required: false
  thumbnail:
    description: ''
    required: false
  footer:
    description: ''
    required: false
  footer_icon:
    description: ''
    required: false
  actions:
    description: ''
    required: false
  event-json:
    description: 'Specify when overriding GitHub events.'
    default: ${{ toJson(github.event) }}
    required: false
outputs:
  result:
    description: '`success` or `failure` is set.'
runs:
  using: 'node12'
  main: 'dist/index.js'
